  
  import type { Metadata } from 'next'
  import { Inter } from 'next/font/google'
  import './globals.css'
  import { Toaster } from "react-hot-toast";

  const inter = Inter({ subsets: ['latin'] })

  export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en" className='light-dark'>
        <body className={inter.className}>
          <Toaster position="top-right" />
          {/* <div className="flex">
      <div className="flex-1 bg-[#182337] min-h-screen p-5">
        <Sidebar />
      </div>
      <div className="flex-[4] p-5">
        <Navbar />
        {children}
      </div>
    </div> */}
          {children}
        </body>
      </html>
    )
  }
